//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restik.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dishes
    {
        public Dishes()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<OrderItems> OrderItems { get; set; }
    }
}
