//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restik.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int ID { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TableNumber { get; set; }
        public Nullable<int> CustomerCount { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
    }
}
